chore(actions): add console output for `prettier-fmt` Actions workflow (#3278)
* chore(actions): add console output for `prettier-fmt` workflow

* chore(actions): move output to the `Fail the job` step

diff --git a/.github/workflows/prettier-fmt.yml b/.github/workflows/prettier-fmt.yml
--- a/.github/workflows/prettier-fmt.yml
+++ b/.github/workflows/prettier-fmt.yml
@@ -84,4 +84,17 @@ jobs:
             <sup>[#${{github.sha}}](https://github.com/medplum/medplum/commits/${{github.sha}})</sup>
       - name: Fail the job
         if: steps.fmt.outputs.prettier_fmt_errs != ''
-        run: exit 1
+        run: |
+          echo "❌ \"prettier\" reported errors"
+          echo ""
+          echo "To one-off fix this manually, run:"
+          echo ""
+          echo "npm run prettier"
+          echo ""
+          echo ""
+          echo "You might need to run \"npm install\" locally and configure your text editor to auto-format on save."
+          echo "See: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode"
+          echo ""
+          echo "https://github.com/medplum/medplum/commits/${{github.sha}}"
+          
+          exit 1
